# Generated by Django 4.1.2 on 2023-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.TextField(default=1, max_length=6, verbose_name='stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='idProducto'),
        ),
    ]
