# Generated by Django 4.1.2 on 2023-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_producto_stock_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.TextField(max_length=20, verbose_name='Categoria'),
        ),
    ]
