# Generated by Django 4.1.2 on 2023-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(null=True, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.CharField(max_length=6, verbose_name='stock'),
        ),
    ]
