# Generated by Django 4.1.2 on 2023-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_producto_categoria_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=False, max_length=6, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank='true', null=True, verbose_name='foto'),
        ),
    ]
