# Generated by Django 4.2.1 on 2023-05-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='idProducto')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre producto')),
                ('stock', models.CharField(max_length=6, verbose_name='stock')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('imagen', models.URLField(blank='true', null=True, verbose_name='foto')),
                ('precio', models.CharField(default=False, max_length=6, verbose_name='precio')),
                ('estado', models.BooleanField(default=False, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
